/**
 * Normalized database schema types for Stellaris DB awareness.
 * Stored as .vectors/db-schema.json in the project root.
 */

export interface DbSchema {
  meta: DbSchemaMeta;
  enums: DbEnum[];
  tables: DbTable[];
}

export interface DbSchemaMeta {
  /** Database provider */
  provider: 'postgres' | 'mysql' | 'sqlite';
  /** How the schema was obtained */
  source: 'introspection' | 'prisma' | 'drizzle' | 'migrations' | 'types';
  /** Database name (no credentials) */
  database: string;
  /** Host only, password stripped */
  connection_host?: string;
  /** ISO timestamp of when the snapshot was taken */
  snapshot_at: string;
  /** Stellaris version that created this snapshot */
  stellaris_version: string;
}

export interface DbEnum {
  name: string;
  /** DB schema namespace (e.g. 'public', 'auth') */
  schema: string;
  values: string[];
}

export interface DbTable {
  name: string;
  /** DB schema namespace (e.g. 'public', 'auth') */
  schema: string;
  comment?: string;
  columns: DbColumn[];
  primary_key: string[];
  indexes: DbIndex[];
  foreign_keys: DbForeignKey[];
  rls_policies: DbRlsPolicy[];
  /** Approximate row count from pg_class.reltuples (may be -1 if not vacuumed) */
  row_count_estimate?: number;
}

export interface DbColumn {
  name: string;
  /** Raw DB type: 'uuid', 'text', 'integer', 'timestamp with time zone', etc. */
  type: string;
  nullable: boolean;
  default_value?: string;
  is_primary_key: boolean;
  is_unique: boolean;
  /** True for GENERATED ALWAYS AS or GENERATED BY DEFAULT AS IDENTITY */
  is_generated: boolean;
  comment?: string;
  /** Reference to DbEnum.name if this column uses an enum type */
  enum_name?: string;
}

export interface DbIndex {
  name: string;
  columns: string[];
  is_unique: boolean;
  /** Index type: 'btree', 'gin', 'gist', 'hash', etc. */
  type: string;
  /** Only for partial indexes */
  where_clause?: string;
}

export interface DbForeignKey {
  name: string;
  columns: string[];
  references_table: string;
  references_schema: string;
  references_columns: string[];
  on_delete: string;
  on_update: string;
}

export interface DbRlsPolicy {
  name: string;
  command: 'SELECT' | 'INSERT' | 'UPDATE' | 'DELETE' | 'ALL';
  /** USING expression */
  using?: string;
  /** WITH CHECK expression */
  with_check?: string;
  /** Roles this policy applies to */
  roles: string[];
  /** true = permissive (default), false = restrictive */
  permissive: boolean;
}
